version: '2'
services:
  node_frontend:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
       - ../frontend:/home/node/app
    ports:
      - '8082:3000'
    command: sh -c "npm rebuild node-sass && npm start"
  node_backend:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ../backend:/home/node/app
    ports:
      - '8081:3008'
    command: "npm start"
    links:
      - mongo
  mongo:
    volumes:
      - ./mongo:/data/db
    image: mongo
    ports:
      - '27017:27017'
    restart: always


